---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    run: {{ .Values.name }}
    test: "{{ now | unixEpoch }}"
  name: {{ .Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    run: {{ .Values.name }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: {{ .Values.name }}
      annotations:
        configTime: "{{ now | unixEpoch }}"  
    spec:
      containers:
      - image: quay.io/redhat-cop/tool-box
        imagePullPolicy: Always
        name: {{ .Values.name }}
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        env: 
        - name: CONFIG_TIME_STAMP
          valueFrom:
            fieldRef: 
              fieldPath: metadata.name
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange

